timetracker/entries/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.RootRedirectView.as_view(), name='root'),
    url(r'^clients/$', views.ClientListView.as_view(), name='client-list'),
    url(r'^clients/create$', views.ClientCreateView.as_view(), name='client-create'),
    url(r'^clients/(?P<pk>\d+)/$', views.ClientDetailView.as_view(), name='client-detail'),
    url(r'^entries/$', views.EntryListView.as_view(), name='entry-list'),
    url(r'^projects/$', views.ProjectListView.as_view(), name='project-list'),
    url(r'^projects/create$', views.ProjectCreateView.as_view(), name='project-create'),
    url(r'^projects/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project-detail'),
]

timetracker/timetracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from entries import urls as entry_urls


urlpatterns = [
    url(r'^', include(entry_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

timetracker/entries/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Client(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('client-detail', kwargs={'pk': self.pk})


class Project(models.Model):
    client = models.ForeignKey('Client', blank=True, null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return '<{}> {}'.format(self.client, self.name)

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'pk': self.pk})


# Create your models here.
class Entry(models.Model):
    start = models.DateTimeField(default=timezone.now)
    stop = models.DateTimeField(blank=True, null=True)
    project = models.ForeignKey('Project')
    description = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return '[{} - {}] ({}) {}'.format(self.start, self.stop, self.project.name, self.description)

    def is_finished(self):
        return self.stop is not None

timetracker/entries/forms.py
from django import forms
from django.utils import timezone

from .models import Project, Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

    #name = forms.CharField()
    #client = forms.ModelChoiceField(queryset=Client.objects.all())


class EntryForm(forms.Form):
    start = forms.DateTimeField(label="Start Time", help_text="Format: 2006-10-25 14:30")
    stop = forms.DateTimeField(label="End Time", help_text="Format: 2006-10-25 14:30")
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    description = forms.CharField()

    def clean_start(self):
        """
        Validation for start field
        """
        start = self.cleaned_data['start']
        if start >= timezone.now():
            raise forms.ValidationError('Start time must be in the past')

        # Must return the value, regardless of whether we changed it or not
        return start

    def clean(self):
        """
        This method handles the validation of the form overall and is useful for
        handling scenarios like when a field relies on another field
        """
        # Call parent's clean method to ensure any validation logic in parent class
        # is preserved
        cleaned_data = super(EntryForm, self).clean()

        # Get the start and end values from the cleaned_data dictionary, or None
        # if the dictionary keys are missing
        start = cleaned_data.get('start', None)
        end = cleaned_data.get('end', None)

        if end and start and (end < start):
            raise forms.ValidationError('End time must come after start time')
        # No need to return anything (Django 1.7 and above)

timetracker/entries/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView, CreateView, RedirectView
from django.core.urlresolvers import reverse_lazy

from .forms import EntryForm, ProjectForm, ClientForm
from .models import Client, Entry, Project

class RootRedirectView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('client-list')

class ClientDetailView(DetailView):
    model = Client
    template_name = 'client_detail.html'

class ClientListView(ListView):
    model = Client
    template_name = 'client_list.html'

class ClientCreateView(CreateView):
    model = Client
    template_name = 'client_create.html'
    form_class = ClientForm

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project_detail.html'

class ProjectListView(ListView):
    model = Project
    template_name = 'project_list.html'

class ProjectCreateView(CreateView):
    model = Project
    template_name = 'project_create.html'
    form_class = ProjectForm

class EntryListView(ListView):
    model = Entry
    template_name = 'entry_list.html'

timetracker/entries/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}TimeTracker{% endblock %}</title>

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <style>
      label {
        width: 100px;
      }
      .errorlist {
        color: red;
      }
    </style>

    {% block style_extra %}{% endblock %}
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">TimeTracker</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'client-list' %}">Clients</a></li>
            <li><a href="{% url 'entry-list' %}">Entries</a></li>
            <li><a href="{% url 'project-list' %}">Projects</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Content -->
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Javascript is placed at the bottom of the page for faster page loads -->
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Global javascript -->
    <script>
    // Set active class on navigation item depending on page url
    $('#navbar ul.navbar-nav li').each(function() {
      if ($(this).find('a').attr('href') === window.location.pathname) {
        $(this).addClass('active');
      } else {
        $(this).removeClass('active');        
      }
    });
    </script>

    {% block script_extra %}{% endblock %}
  </body>
</html>

timetracker/entries/templates/client_detail.html
{% extends "base.html" %}

{% block title %}Client projects{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>Client projects</h2>
  </div>

  <h3>Client</h3>

  {% include 'snippets/form_default.html' with form_title='Change Client' form_submit_label='Update' %}  

  <h3>Projects</h3>
  <ul class="list-unstyled col-md-6 pull-left" style="padding: 0;">
    {% for project in client.project_set.all %}
      <li class="panel panel-default">
        <div class="panel-heading">
          {{ project.name }}
        </div>
        <ul class="list-group">
          {% for entry in project.entry_set.all %}
            <li class="list-group-item">{{ entry.description }}</li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/clients.html
{% extends "base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>Clients</h2>
  </div>

  {% include 'snippets/form_default.html' with form_title='New Client' form_submit_label='Create' %}

  <ul class="list-group col-md-3">
    {% for client in client_list %}
      <li class="list-group-item">
        <a href="{% url 'client-detail' pk=client.pk %}">{{ client.name }}</a>
        <a class="btn btn-warning btn-xs pull-right" href="{% url 'client-detail' pk=client.pk %}">Edit</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/entries.html
{% extends "base.html" %}

{% block title %}Entries{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>Entries</h2>
  </div>

  <div class="panel panel-default">

    <div class="panel-heading">
      <h3 class="panel-title">New Entry</h3>
    </div>

    <div class="panel-body">
      <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ entry_form.as_p }}
        <input class="btn btn-primary" type="submit" name="name" value="Create Entry">
      </form>
    </div>

  </div>

  <ul class="list-group col-md-3">
    {% for entry in entry_list %}
      <li class="list-group-item">{{ entry.description }}</li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/project_detail.html
{% extends "base.html" %}

{% block title %}Project - {{ project.name }}{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>Project - {{ project.name }}</h2>
  </div>

  {% include 'snippets/form_default.html' with form_title='Edit Project' form_submit_label='Update' %}

  <h3>Details</h3>
  <ul class="list-unstyled col-md-6 pull-left" style="padding: 0;">
    <li><label>Name</label>{{ project.name }}</li>
    <li><label>Client</label><a href="{% url 'client-detail' pk=project.client.pk %}">{{ project.client }}</a></li>
  </ul>
{% endblock %}

timetracker/entries/templates/projects.html
{% extends "base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>Projects</h2>
  </div>

  {% include 'snippets/form_default.html' with form_title='New Project' form_submit_label='Create Project' %}

  <ul class="list-group col-md-3">
    {% for project in project_list %}
      <li class="list-group-item">
        <a href="{% url 'project-detail' pk=project.pk %}">{{ project.name }}</a> (<a href="{% url 'client-detail' pk=project.client.pk %}">{{ project.client.name }}</a>)
        <a class="btn btn-warning btn-xs pull-right" href="{% url 'project-detail' pk=project.pk %}">Edit</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/snippets/form_default.html
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">{{ form_title }}</h3>
  </div>

  <div class="panel-body">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" name="submit" value="{{ form_submit_label }}">
    </form>
  </div>

</div>